scalafix Any2StringAdd prepare
Remove an unused local variable that cause error when scalafix Any2StringAdd

```
scalafix.internal.v1.FileException: unexpected error processing file /Users/thanhbv/ohze/oss/akka/akka-bench-jmh/src/main/scala/akka/actor/TellOnlyBenchmark.scala
Caused by: org.scalameta.UnreachableError: this code path should've been unreachable
	at org.scalameta.UnreachableError$.raise(package.scala:40)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.isAmbiguousWithPatVarTerm$1(TreeSyntax.scala:251)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.guessIsBackquoted(TreeSyntax.scala:273)
  | => aat scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$syntaxTree$1(TreeSyntax.scala:331)
	at scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	at scala.meta.internal.prettyprinters.TreeSyntax$.$anonfun$apply$1(TreeSyntax.scala:1018)
	at scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	at scala.meta.prettyprinters.Api$XtensionSyntax.syntax(Api.scala:11)
	at scalafix.internal.v1.TreePos$.symbol(TreePos.scala:9)
	at scalafix.internal.v1.InternalSemanticDoc.fromTextDocument$1(InternalSemanticDoc.scala:53)
	at scalafix.internal.v1.InternalSemanticDoc.symbol(InternalSemanticDoc.scala:60)
	at scalafix.v1.package$XtensionTreeScalafix.symbol(package.scala:12)
	at scalafix.v1.SymbolMatcher.unapply(SymbolMatcher.scala:16)
	at scalafix.v1.SymbolMatcher.unapply$(SymbolMatcher.scala:15)
	at scalafix.v1.SymbolMatcher$$anon$2.unapply(SymbolMatcher.scala:29)
	at fix.Any2StringAdd$$anonfun$fix$1.applyOrElse(/Users/thanhbv/ohze/oss/scalafix-rules/scalafix/rules/src/main/scala/fix/Any2StringAdd.scala:41)
```