Changed osgi test framework to Karaf.
Using [paxexam-karaf](https://github.com/openengsb/labs-paxexam-karaf/wiki)

Still not running due to dependency conflict on "commons-io:commons-io:2.0.1" and "org.apache.commons:commons-io:1.3.2"
Error:

```scala

{file:/home/muki/Development/workspace_play/akka/}akka-osgi-tests/*:update: sbt.ResolveException: unresolved dependency: org.apache.commons#commons-io;1.3.2: java.text.ParseException: inconsistent module descriptor file found in 'http://repo1.maven.org/maven2/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.pom': bad organisation: expected='org.apache.commons' found='commons-io';
```
[pom.xml](https://github.com/openengsb/labs-paxexam-karaf/blob/master/pom.xml) which declares dependencies.

The `scalatest.org` bundle exports it's dependencies in an unproper way, so karaf can't deploy the bundle.
The following exception is thrown

```java

karaf@root> 2012-08-03 09:54:36,676 | ERROR | .pax/exam/deploy | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.2.4 | Failed to install artifact: /home/muki/.pax/exam/deploy/abac942f-8cef-45b9-aff2-6a896987415b_1.9-2.10.0-M5-B2.jar
org.osgi.framework.BundleException: Could not create bundle object.
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2592)[org.apache.felix.framework-3.0.9.jar:]
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2443)[org.apache.felix.framework-3.0.9.jar:]
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:129)[org.apache.felix.framework-3.0.9.jar:]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.installOrUpdateBundle(DirectoryWatcher.java:1027)[6:org.apache.felix.fileinstall:3.2.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:941)[6:org.apache.felix.fileinstall:3.2.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:854)[6:org.apache.felix.fileinstall:3.2.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:483)[6:org.apache.felix.fileinstall:3.2.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:291)[6:org.apache.felix.fileinstall:3.2.4]
Caused by: java.lang.NumberFormatException: For input string: "0-M5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)[:1.7.0_04]
	at java.lang.Integer.parseInt(Integer.java:492)[:1.7.0_04]
	at java.lang.Integer.parseInt(Integer.java:527)[:1.7.0_04]
	at org.osgi.framework.Version.<init>(Version.java:133)[karaf.jar:2.2.8]
	at org.apache.felix.framework.util.VersionRange.parse(VersionRange.java:92)[org.apache.felix.framework-3.0.9.jar:]
	at org.apache.felix.framework.util.manifestparser.ManifestParser.normalizeImportClauses(ManifestParser.java:268)[org.apache.felix.framework-3.0.9.jar:]
	at org.apache.felix.framework.util.manifestparser.ManifestParser.<init>(ManifestParser.java:145)[org.apache.felix.framework-3.0.9.jar:]
	at org.apache.felix.framework.ModuleImpl.<init>(ModuleImpl.java:243)[org.apache.felix.framework-3.0.9.jar:]
	at org.apache.felix.framework.BundleImpl.createModule(BundleImpl.java:1153)[org.apache.felix.framework-3.0.9.jar:]
	at org.apache.felix.framework.BundleImpl.<init>(BundleImpl.java:79)[org.apache.felix.framework-3.0.9.jar:]
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2535)[org.apache.felix.framework-3.0.9.jar:]
	... 7 more

```

I created a custom `scalatest.jar` which runs and upload it to my server. I think this problem
will disappear, when scala 2.10 is out in a final version.