Fix Name clash dotty compile error in akka-actor's akka.util.Index
```
error] -- [E120] Duplicate Symbol Error: /Users/thanhbv/ohze/oss/akka/akka-actor/src/main/scala/akka/util/Index.scala:25:18
[error] 25 |    this(mapSize, new Comparator[V] {
[error]    |                  ^
[error]    |Name clash between defined and inherited member:
[error]    |def compare(x$0: T, x$1: T): Int in trait Comparator and
[error]    |def compare(a: V, b: V): Int in anonymous class Object with java.util.Comparator[V] {...} at line 26
[error]    |have the same type after erasure.
```